monitor.bluez.rules = [
    {
        matches = [
            { device.name = "~bluez_card.*" }
        ]
        actions = {
            update-props = {
                bluez5.auto-connect  = [ hfp_hf hsp_hs a2dp_sink a2dp_source ]
                bluez5.hw-volume     = [ hfp_hf hsp_hs a2dp_sink ]
                device.profile       = "headset-head-unit"
            }
        }
    }
]
