### Layout ###
legacy_layout=0
horizontal

### Metrics ###
fps
cpu_temp
gpu_temp

### Appearance ###
position=top-right
font_size=22
background_alpha=0.35
round_corners=10

### Colors ###
text_color=FFFFFF

### Controls ###
toggle_hud=Shift_R+F12
