### FPS ###
fps
fps_metrics=avg,0.01
frametime=0

### GPU ###
gpu_stats
gpu_temp
vram

### CPU ###
cpu_stats
cpu_temp

### RAM ###
ram

### Appearance ###
position=top-right
font_size=22
background_alpha=0.35
round_corners=10

### Colors ###
text_color=FFFFFF

### Controls ###
toggle_hud=Shift_R+F12
