# Wayland natif
vo=gpu
gpu-context=wayland
hwdec=auto

# Audio via pipewire
ao=pipewire

# Interface
border=no
keepaspect=yes
cursor-autohide=1000

# Sous-titres
sub-auto=fuzzy
slang=fr,en

# Qualité
scale=lanczos

# Sync audio/video
video-sync=display-resample
interpolation=yes
tscale=oversample

# Buffer pipewire
audio-buffer=0.1
audio-stream-silence=yes

# Correction de dérive
af=scaletempo2
