# =========================
# FORMAT GLOBAL
# =========================
format = """
$os\

[](fg:white)\
${custom.context}\
$username\
$directory\
[](fg:blue)\

$git_branch\
$git_status\
$docker_context\
$python\
$nodejs\
$java\
$rust\
$golang\
$c\
$cmd_duration\
$line_break\
$character
"""

add_newline = false
# =========================
# OS
# =========================
[os]
disabled = false
format = "[$symbol $os](bold white) "

[os.symbols]
Arch = ""
Fedora = ""
Linux = ""
Macos = ""
Windows = ""

# =========================
# MODULE CUSTOM (Distant vs Local)
# =========================
[custom.context]
command = "echo $PROMPT_CONTEXT" 
format = "[$output ](bg:white fg:bold black)"
when = "true"
# =========================
# USER (pill vert avec coins)
# =========================
[username]
format = "[$user ](bg:white fg:bold black)"
show_always = true

# =========================
# DIRECTORY (pill bleu avec coins)
# =========================
[directory]
format = "[ $path](bg:blue fg:bold white)"
truncation_length = 3
truncate_to_repo = true

# =========================
# GIT
# =========================
[git_branch]
symbol = ""
format = "[ $symbol $branch ](bold purple)"

[git_status]
format = "[ $all_status$ahead_behind ](bold red)"

# =========================
# LANGAGES
# =========================
[python]
format = "[ py $version ](yellow)"

[nodejs]
format = "[ node $version ](green)"

[java]
format = "[ java $version ](red)"

[rust]
format = "[ rs $version ](red)"

[golang]
format = "[ go $version ](cyan)"

[c]
format = ""

# =========================
# DEVOPS / ENV
# =========================
[docker_context]
format = "[ docker $context ](blue)"

[kubernetes]
format = "[ k8s $context ](cyan)"

# =========================
# PERF
# =========================
[cmd_duration]
min_time = 2000
format = "[ $duration ](dimmed yellow)"

# =========================
# PROMPT
# =========================
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
