#!/usr/bin/env bash
set -euo pipefail

# =========================================================
# display-layout.sh — UI (wheel + waybar module; rofi menu kept as a
# fallback/reference) for display layout. Same pattern as
# set_wallpaper.sh / hdr.sh: this UI only writes the JSON state, it's
# scripts/workspace-manager.sh (the engine) that applies it.
#
#   display-layout.sh roue-gen -> regenerates ~/.config/roue/wheels/display.toml
#                                  (SUPER+O, see hypr/keybinds.lua) then
#                                  `roue display` shows the wheel
#   display-layout.sh apply M  -> applies mode M ("both"/"internal"/
#                                  "external"), triggered by a sector of
#                                  the wheel generated above
#   display-layout.sh menu     -> old multi-step rofi menu (position +
#                                  alignment included), left in place
#   display-layout.sh status   -> JSON for the waybar module
#
# Role resolution (internal/external) duplicated here in a minimal,
# read-only version, just to know which options to offer/display — the
# application logic stays entirely in workspace-manager.sh (single
# source of truth).
#
# The wheel generated by roue-gen ONLY offers the mode choice (All /
# internal / external) -- position and alignment, adjustable via the old
# rofi menu if needed, aren't asked again every time (see cmd_apply):
# they stay whatever is already stored in display-layout.json.
# =========================================================

STATE_FILE="$HOME/.config/hypr/display-layout.json"
RASI="$HOME/.config/rofi/wallpaper-mode.rasi"
# nf-md-monitor -- GTK/waybar doesn't support the ::before CSS selector
# ("Invalid name of pseudo-class"), so the "display" group's icon
# (display+scale+hdr) is injected here, at the start of the trio's 1st
# module.
ICON="󰍹"
WAYBAR_SIGNAL=4

# Internal panel connector read from DRM rather than via `hyprctl
# monitors`, which loses the panel as soon as it's offline. Reading from
# DRM avoids the fallback below misclassifying the external screen as
# internal in "external only" mode (panel off, so absent from monitor
# data), which would make it impossible to switch back to the internal
# display. Dynamic resolution (follows the real connector, never
# hardcoded). Same helper duplicated in workspace-manager.sh (the
# engine's source of truth).
internal_from_drm() {
    local d
    # 1) CONNECTED internal connector = this boot's real panel. Handles the
    #    dual-GPU MUX (the panel can appear as card1-eDP-* or card2-eDP-*
    #    depending on the routing chosen at boot): checking the status is
    #    necessary, since the glob's first connector can be a ghost
    #    connector from a GPU not used this boot.
    for d in /sys/class/drm/card*-eDP-* /sys/class/drm/card*-LVDS-* /sys/class/drm/card*-DSI-*; do
        [[ -e "$d" ]] || continue
        [[ "$(cat "$d/status" 2>/dev/null)" == connected ]] || continue
        basename "$d" | sed -E 's/^card[0-9]+-//'
        return 0
    done
    # 2) Fallback: any internal connector, even disabled — avoids getting
    #    stuck in "external only" mode (panel off, absent from the first
    #    pattern above, but still ours).
    for d in /sys/class/drm/card*-eDP-* /sys/class/drm/card*-LVDS-* /sys/class/drm/card*-DSI-*; do
        [[ -e "$d" ]] || continue
        basename "$d" | sed -E 's/^card[0-9]+-//'
        return 0
    done
}

resolve_roles() {
    # NB: in this function, prefer `if [[ cond ]]; then var=val; fi` over
    # the short form `[[ cond ]] && var=val`. Under `set -e`, if this short
    # form is the last instruction executed in the function and the
    # condition is false, the `&&` makes the function exit with a nonzero
    # status, which silently terminates the whole script — including in
    # the most common case where the condition is false simply because no
    # fallback is needed.
    local internal
    mons_json="$(hyprctl monitors all -j)"
    internal="$(internal_from_drm)"
    if [[ -z "$internal" ]]; then
        internal="$(jq -r '[.[] | select(.name | test("^(eDP|LVDS|DSI)"))][0].name // empty' <<<"$mons_json")"
    fi
    if [[ -z "$internal" ]]; then
        internal="$(jq -r '.[0].name // empty' <<<"$mons_json")"
    fi
    first_external="$(jq -r --arg m "$internal" '[.[] | select(.name != $m)][0].name // empty' <<<"$mons_json")"

    # Names shown in the menu: the internal panel has no usable
    # "consumer-friendly" name (its EDID description is the panel
    # manufacturer, e.g. "Chimei Innolux ..."), hence a fixed generic
    # label. The external one, on the other hand, has a real brand name in
    # its EDID description: its first word is extracted dynamically (never
    # hardcoded — follows whatever screen is actually plugged in).
    internal_label="Laptop"
    external_label="Externe"
    if [[ -n "$first_external" ]]; then
        external_label="$(jq -r --arg m "$first_external" '.[] | select(.name==$m) | .description // empty' <<<"$mons_json" | awk '{print $1}')"
        if [[ -z "$external_label" ]]; then
            external_label="Externe"
        fi
    fi
}

current_state() {
    mode="both"; position="external-left"; align="center"
    if [[ -f "$STATE_FILE" ]]; then
        local v
        v="$(jq -r '.mode // empty'     "$STATE_FILE" 2>/dev/null || true)"
        if [[ "$v" =~ ^(both|internal|external)$ ]]; then mode="$v"; fi
        v="$(jq -r '.position // empty' "$STATE_FILE" 2>/dev/null || true)"
        if [[ "$v" =~ ^(external-left|external-right)$ ]]; then position="$v"; fi
        v="$(jq -r '.align // empty'    "$STATE_FILE" 2>/dev/null || true)"
        if [[ "$v" =~ ^(center|top|bottom)$ ]]; then align="$v"; fi
    fi
}

write_state() {
    python3 -c "
import json
with open('$STATE_FILE', 'w') as f:
    json.dump({'mode': '$1', 'position': '$2', 'align': '$3'}, f)
"
}

refresh_bar() { pkill -RTMIN+"$WAYBAR_SIGNAL" waybar 2>/dev/null || true; }

# Applies a mode directly (triggered from a wheel sector, see
# cmd_roue_gen) -- position/align are NOT asked again here, unlike
# cmd_menu: whatever is already stored is reused as-is (current_state,
# with its own defaults if the state file is absent). Picking "All"
# repeatedly must not reset a layout the user already configured.
cmd_apply() {
    local new_mode="$1"
    resolve_roles
    current_state
    write_state "$new_mode" "$position" "$align"
    bash ~/.config/hypr/scripts/workspace-manager.sh
    refresh_bar
}

# Generates ~/.config/roue/wheels/display.toml right before opening the
# wheel (see keybinds.lua) -- THIS wheel has no config fixed in the repo:
# its sectors (which external screen, whether one is even plugged in)
# depend on the hardware actually detected at that moment, so it's this
# script -- the same detection logic as cmd_menu (resolve_roles) -- that
# writes the TOML on every press, not a static file. Gitignored file (see
# .gitignore): it's a runtime artifact, not versioned config, same status
# as display-layout.json.
cmd_roue_gen() {
    resolve_roles
    current_state

    if [[ -z "$first_external" ]]; then
        notify-send "Displays" "No external screen detected — only one screen active."
        exit 1
    fi

    local dir="$HOME/.config/roue/wheels"
    mkdir -p "$dir"
    # Minimal TOML escaping -- labels come from EDID (brand name), never
    # user input, but a literal quote there would still break parsing
    # without this.
    local internal_esc="${internal_label//\"/\\\"}"
    local external_esc="${external_label//\"/\\\"}"

    # Only one "active = true" sector, the one matching the currently
    # applied $mode (see current_state) -- shows the state band on the
    # wheel (see roue-src/src/wheel.rs). Recomputed on every call: that's
    # exactly why this file is regenerated on every open rather than fixed,
    # see this function's doc above.
    local active_all="" active_internal="" active_external=""
    case "$mode" in
        both)     active_all="active = true" ;;
        internal) active_internal="active = true" ;;
        external) active_external="active = true" ;;
    esac

    # confirm = true everywhere -- changing the display layout can
    # move/cut off the active window from one edge to another, not just
    # refresh a display: better to confirm than undo by accident. No
    # confirm_accent (see config.rs): unlike power.toml, nothing here is
    # destructive -- the cyan default is enough, still with the hub border
    # on Confirm hover (handled by wheel.rs independently of the color).
    cat > "$dir/display.toml" <<EOF
title = "Displays"

[[segment]]
icon = "columns-2.svg"
label = "All"
action = "$HOME/.config/hypr/scripts/display-layout.sh apply both"
confirm = true
$active_all

[[segment]]
icon = "laptop.svg"
label = "$internal_esc"
action = "$HOME/.config/hypr/scripts/display-layout.sh apply internal"
confirm = true
$active_internal

[[segment]]
icon = "monitor.svg"
label = "$external_esc"
action = "$HOME/.config/hypr/scripts/display-layout.sh apply external"
confirm = true
$active_external
EOF
}

cmd_menu() {
    resolve_roles
    current_state

    if [[ -z "$first_external" ]]; then
        notify-send "Displays" "No external screen detected — only one screen active."
        exit 0
    fi

    local choice new_mode
    choice=$(printf "All\n%s\n%s" "$internal_label" "$external_label" | rofi -dmenu \
        -theme "$RASI" -theme-str 'listview { columns: 3; }' \
        -mesg "Displays" -name "display-picker" -no-show-icons -no-custom -lines 1)
    [[ -z "$choice" ]] && exit 0
    case "$choice" in
        "All")             new_mode="both" ;;
        "$internal_label") new_mode="internal" ;;
        "$external_label") new_mode="external" ;;
        *)                 exit 0 ;;
    esac

    local new_position="$position" new_align="$align"
    if [[ "$new_mode" == "both" ]]; then
        choice=$(printf "%s à gauche\n%s à droite" "$external_label" "$external_label" | rofi -dmenu \
            -theme "$RASI" \
            -mesg "Position" -name "display-picker" -no-show-icons -no-custom -lines 1)
        [[ -z "$choice" ]] && exit 0
        [[ "$choice" == "$external_label à gauche" ]] && new_position="external-left" || new_position="external-right"

        choice=$(printf "Centré\nHaut\nBas" | rofi -dmenu \
            -theme "$RASI" -theme-str 'listview { columns: 3; }' \
            -mesg "Alignment" -name "display-picker" -no-show-icons -no-custom -lines 1)
        [[ -z "$choice" ]] && exit 0
        case "$choice" in
            "Centré") new_align="center" ;;
            "Haut")   new_align="top" ;;
            "Bas")    new_align="bottom" ;;
        esac
    fi

    write_state "$new_mode" "$new_position" "$new_align"
    bash ~/.config/hypr/scripts/workspace-manager.sh
    refresh_bar
}

cmd_status() {
    resolve_roles
    current_state

    local label tooltip
    case "$mode" in
        internal) label="int" ;;
        external) label="ext" ;;
        *)        label="all" ;;
    esac

    if [[ "$mode" == "both" && -z "$first_external" ]]; then
        tooltip="Internal only (no external detected)\\nClick: change layout"
    elif [[ "$mode" == "both" ]]; then
        tooltip="Both screens · ${position} · ${align}\\nClick: change layout"
    else
        tooltip="${label} · Click: change layout"
    fi

    printf '{"text":"%s %s","class":"display-%s","tooltip":"%s"}\n' "$ICON" "$label" "$mode" "$tooltip"
}

case "${1:-status}" in
    menu)     cmd_menu ;;
    status)   cmd_status ;;
    apply)    cmd_apply "$2" ;;
    roue-gen) cmd_roue_gen ;;
    *)        echo "usage: $0 {menu|status|apply MODE|roue-gen}" >&2; exit 1 ;;
esac
