#!/usr/bin/env bash
set -euo pipefail

# =========================================================
# display-layout.sh — UI (wheel + waybar module; rofi menu kept as a
# fallback/reference) for display layout. Same pattern as
# set_wallpaper.sh / hdr.sh: this UI only writes the JSON state, it's
# scripts/workspace-manager.sh (the engine) that applies it.
#
#   display-layout.sh roue-gen -> regenerates ~/.config/roue/wheels/display.toml
#                                  (SUPER+O, see hypr/keybinds.lua) then
#                                  `roue display` shows the wheel
#   display-layout.sh apply M  -> applies mode M ("both"/"internal"/
#                                  "external"), triggered by a sector of
#                                  the wheel generated above
#   display-layout.sh menu     -> old rofi menu (just the mode choice now)
#   display-layout.sh swap     -> swaps internal/external in
#                                  monitor-layout.json's grid -- the quick
#                                  fix for "I physically swapped which
#                                  side the external screen is on"
#   display-layout.sh status   -> JSON for the waybar module
#
# Role resolution (internal/external) duplicated here in a minimal,
# read-only version, just to know which options to offer/display — the
# application logic stays entirely in workspace-manager.sh (single
# source of truth).
#
# WHERE each screen sits (side by side, stacked, or a real grid for a 3rd+
# screen) is no longer asked here at all -- that used to be a 2-step rofi
# prompt (position + alignment) writing "external-left"/"external-right"
# into display-layout.json, which broke every time the external screen
# and the laptop swapped physical sides. It's now a hand-edited file,
# ~/.config/hypr/monitor-layout.json (see workspace-manager.sh's header
# for the schema) -- this script only still offers `swap` as a shortcut
# for the single most common edit to that file.
#
# The wheel generated by roue-gen ONLY offers the mode choice (All /
# internal / external), same as before.
# =========================================================

STATE_FILE="$HOME/.config/hypr/display-layout.json"
LAYOUT_FILE="$HOME/.config/hypr/monitor-layout.json"
RASI="$HOME/.config/rofi/wallpaper-mode.rasi"
WAYBAR_SIGNAL=4

# Internal panel connector read from DRM rather than via `hyprctl
# monitors`, which loses the panel as soon as it's offline. Reading from
# DRM avoids the fallback below misclassifying the external screen as
# internal in "external only" mode (panel off, so absent from monitor
# data), which would make it impossible to switch back to the internal
# display. Dynamic resolution (follows the real connector, never
# hardcoded). Same helper duplicated in workspace-manager.sh (the
# engine's source of truth).
internal_from_drm() {
    local d
    # 1) CONNECTED internal connector = this boot's real panel. Handles the
    #    dual-GPU MUX (the panel can appear as card1-eDP-* or card2-eDP-*
    #    depending on the routing chosen at boot): checking the status is
    #    necessary, since the glob's first connector can be a ghost
    #    connector from a GPU not used this boot.
    for d in /sys/class/drm/card*-eDP-* /sys/class/drm/card*-LVDS-* /sys/class/drm/card*-DSI-*; do
        [[ -e "$d" ]] || continue
        [[ "$(cat "$d/status" 2>/dev/null)" == connected ]] || continue
        basename "$d" | sed -E 's/^card[0-9]+-//'
        return 0
    done
    # 2) Fallback: any internal connector, even disabled — avoids getting
    #    stuck in "external only" mode (panel off, absent from the first
    #    pattern above, but still ours).
    for d in /sys/class/drm/card*-eDP-* /sys/class/drm/card*-LVDS-* /sys/class/drm/card*-DSI-*; do
        [[ -e "$d" ]] || continue
        basename "$d" | sed -E 's/^card[0-9]+-//'
        return 0
    done
}

resolve_roles() {
    # NB: in this function, prefer `if [[ cond ]]; then var=val; fi` over
    # the short form `[[ cond ]] && var=val`. Under `set -e`, if this short
    # form is the last instruction executed in the function and the
    # condition is false, the `&&` makes the function exit with a nonzero
    # status, which silently terminates the whole script — including in
    # the most common case where the condition is false simply because no
    # fallback is needed.
    local internal
    mons_json="$(hyprctl monitors all -j)"
    internal="$(internal_from_drm)"
    if [[ -z "$internal" ]]; then
        internal="$(jq -r '[.[] | select(.name | test("^(eDP|LVDS|DSI)"))][0].name // empty' <<<"$mons_json")"
    fi
    if [[ -z "$internal" ]]; then
        internal="$(jq -r '.[0].name // empty' <<<"$mons_json")"
    fi
    first_external="$(jq -r --arg m "$internal" '[.[] | select(.name != $m)][0].name // empty' <<<"$mons_json")"

    # Names shown in the menu: the internal panel has no usable
    # "consumer-friendly" name (its EDID description is the panel
    # manufacturer, e.g. "Chimei Innolux ..."), hence a fixed generic
    # label. The external one, on the other hand, has a real brand name in
    # its EDID description: its first word is extracted dynamically (never
    # hardcoded — follows whatever screen is actually plugged in).
    internal_label="Laptop"
    external_label="Externe"
    if [[ -n "$first_external" ]]; then
        external_label="$(jq -r --arg m "$first_external" '.[] | select(.name==$m) | .description // empty' <<<"$mons_json" | awk '{print $1}')"
        if [[ -z "$external_label" ]]; then
            external_label="Externe"
        fi
    fi
}

current_state() {
    mode="both"; main="internal"
    if [[ -f "$STATE_FILE" ]]; then
        local v
        v="$(jq -r '.mode // empty' "$STATE_FILE" 2>/dev/null || true)"
        if [[ "$v" =~ ^(both|internal|external)$ ]]; then mode="$v"; fi
        v="$(jq -r '.main // empty' "$STATE_FILE" 2>/dev/null || true)"
        if [[ "$v" =~ ^(internal|external)$ ]]; then main="$v"; fi
    fi
}

write_state() {
    python3 -c "
import json
with open('$STATE_FILE', 'w') as f:
    json.dump({'mode': '$1', 'main': '$2'}, f)
"
}

# Which screen counts as "main" (see workspace-manager.sh's header comment
# for why this matters: it decides who keeps workspaces 1-5 once both
# screens are back). Auto-tracked, not a separate menu entry: picking a
# SOLO mode (internal/external) makes that screen main going forward --
# picking "both" just reuses whatever main already was, unchanged.
resolve_main() {
    local requested_mode="$1" current_main="$2"
    if [[ "$requested_mode" == "internal" || "$requested_mode" == "external" ]]; then
        echo "$requested_mode"
    else
        echo "$current_main"
    fi
}

refresh_bar() { pkill -RTMIN+"$WAYBAR_SIGNAL" waybar 2>/dev/null || true; }

# Applies a mode directly (triggered from a wheel sector, see
# cmd_roue_gen) -- geometry lives entirely in monitor-layout.json now
# (see this file's header), untouched here.
cmd_apply() {
    local new_mode="$1"
    resolve_roles
    current_state
    local new_main
    new_main="$(resolve_main "$new_mode" "$main")"
    write_state "$new_mode" "$new_main"
    bash ~/.config/hypr/scripts/workspace-manager.sh
    refresh_bar
}

# Swaps internal <-> external in monitor-layout.json's grid -- the
# targeted fix for "I temporarily swapped which side the external screen
# is physically on": rather than a left/right enum that goes stale the
# moment the physical arrangement changes, the grid just gets the same
# two roles exchanged wherever they currently sit (works for a horizontal
# row, a vertical column, or either axis of a real grid). Only
# touches those two roles -- any 3rd+ screen already in the grid keeps
# its own cell untouched.
cmd_swap() {
    python3 -c "
import json
path = '$LAYOUT_FILE'
try:
    with open(path) as f:
        data = json.load(f)
except (FileNotFoundError, json.JSONDecodeError):
    data = {}
grid = data.get('grid') or [['external', 'internal']]
pos = {}
for r, row in enumerate(grid):
    for c, role in enumerate(row):
        if role in ('internal', 'external'):
            pos[role] = (r, c)
if 'internal' in pos and 'external' in pos:
    (ri, ci), (re, ce) = pos['internal'], pos['external']
    grid[ri][ci], grid[re][ce] = grid[re][ce], grid[ri][ci]
data['grid'] = grid
with open(path, 'w') as f:
    json.dump(data, f, indent=2)
    f.write('\n')
"
    bash ~/.config/hypr/scripts/workspace-manager.sh
    refresh_bar
    notify-send "Displays" "Layout swapped" 2>/dev/null || true
}

# Generates ~/.config/roue/wheels/display.toml right before opening the
# wheel (see keybinds.lua) -- THIS wheel has no config fixed in the repo:
# its sectors (which external screen, whether one is even plugged in)
# depend on the hardware actually detected at that moment, so it's this
# script -- the same detection logic as cmd_menu (resolve_roles) -- that
# writes the TOML on every press, not a static file. Gitignored file (see
# .gitignore): it's a runtime artifact, not versioned config, same status
# as display-layout.json.
cmd_roue_gen() {
    resolve_roles
    current_state

    if [[ -z "$first_external" ]]; then
        notify-send "Displays" "No external screen detected — only one screen active."
        exit 1
    fi

    local dir="$HOME/.config/roue/wheels"
    mkdir -p "$dir"
    # Minimal TOML escaping -- labels come from EDID (brand name), never
    # user input, but a literal quote there would still break parsing
    # without this.
    local internal_esc="${internal_label//\"/\\\"}"
    local external_esc="${external_label//\"/\\\"}"

    # Only one "active = true" sector, the one matching the currently
    # applied $mode (see current_state) -- shows the state band on the
    # wheel (see roue-src/src/wheel.rs). Recomputed on every call: that's
    # exactly why this file is regenerated on every open rather than fixed,
    # see this function's doc above.
    local active_all="" active_internal="" active_external=""
    case "$mode" in
        both)     active_all="active = true" ;;
        internal) active_internal="active = true" ;;
        external) active_external="active = true" ;;
    esac

    # confirm = true everywhere -- changing the display layout can
    # move/cut off the active window from one edge to another, not just
    # refresh a display: better to confirm than undo by accident. No
    # confirm_accent (see config.rs): unlike power.toml, nothing here is
    # destructive -- the cyan default is enough, still with the hub border
    # on Confirm hover (handled by wheel.rs independently of the color).
    cat > "$dir/display.toml" <<EOF
title = "Displays"

[[segment]]
icon = "columns-2.svg"
label = "All"
action = "$HOME/.config/hypr/scripts/display-layout.sh apply both"
confirm = true
$active_all

[[segment]]
icon = "laptop.svg"
label = "$internal_esc"
action = "$HOME/.config/hypr/scripts/display-layout.sh apply internal"
confirm = true
$active_internal

[[segment]]
icon = "monitor.svg"
label = "$external_esc"
action = "$HOME/.config/hypr/scripts/display-layout.sh apply external"
confirm = true
$active_external
EOF
}

cmd_menu() {
    resolve_roles
    current_state

    if [[ -z "$first_external" ]]; then
        notify-send "Displays" "No external screen detected — only one screen active."
        exit 0
    fi

    local choice new_mode
    choice=$(printf "All\n%s\n%s" "$internal_label" "$external_label" | rofi -dmenu \
        -theme "$RASI" -theme-str 'listview { columns: 3; }' \
        -mesg "Displays" -name "display-picker" -no-show-icons -no-custom -lines 1)
    [[ -z "$choice" ]] && exit 0
    case "$choice" in
        "All")             new_mode="both" ;;
        "$internal_label") new_mode="internal" ;;
        "$external_label") new_mode="external" ;;
        *)                 exit 0 ;;
    esac

    local new_main
    new_main="$(resolve_main "$new_mode" "$main")"
    write_state "$new_mode" "$new_main"
    bash ~/.config/hypr/scripts/workspace-manager.sh
    refresh_bar
}

# Short human-readable rendering of monitor-layout.json's grid, e.g.
# "external | internal" (horizontal) or "external / internal" (vertical)
# -- just enough for the tooltip to hint at the current arrangement
# without duplicating workspace-manager.sh's own default-grid logic here.
grid_desc() {
    if [[ ! -f "$LAYOUT_FILE" ]]; then
        echo "défaut"
        return
    fi
    jq -r '.grid // [] | map(map(if . == null then "·" else . end) | join(" | ")) | join(" / ")' \
        "$LAYOUT_FILE" 2>/dev/null || echo "défaut"
}

cmd_status() {
    resolve_roles
    current_state

    # Icon carries the state now (was a fixed nf-md-monitor + "all"/"int"/
    # "ext" text label): laptop-only, monitor-only, or both-screens split.
    # GTK/waybar doesn't support ::before, so this is a plain state pick,
    # not an injected prefix.
    local icon tooltip
    case "$mode" in
        internal) icon="󰌢" ;;  # nf-md-laptop
        external) icon="󰍹" ;;  # nf-md-monitor
        *)        icon="󰍺" ;;  # nf-md-monitor_multiple (both)
    esac

    if [[ "$mode" == "both" && -z "$first_external" ]]; then
        tooltip="Internal only (no external detected)\\nClick: change layout"
    elif [[ "$mode" == "both" ]]; then
        tooltip="Both screens · $(grid_desc)\\nClick: change layout"
    else
        tooltip="${mode} · Click: change layout"
    fi

    printf '{"text":"%s","class":"display-%s","tooltip":"%s"}\n' "$icon" "$mode" "$tooltip"
}

case "${1:-status}" in
    menu)     cmd_menu ;;
    status)   cmd_status ;;
    apply)    cmd_apply "$2" ;;
    swap)     cmd_swap ;;
    roue-gen) cmd_roue_gen ;;
    *)        echo "usage: $0 {menu|status|apply MODE|swap|roue-gen}" >&2; exit 1 ;;
esac
