-- ============================================================
-- monitors.lua — Dynamic multi-monitor & HDR configuration
-- ============================================================
-- No connector name hardcoded here: workspace assignment (1-7 internal
-- / 8-10 external) and the external monitor's scale/HDR tuning are
-- resolved BY ROLE (internal = eDP*/LVDS*/DSI*, external = everything
-- else) by scripts/workspace-manager.sh.
--
-- IMPORTANT: this file only sets the base output modes at runtime
-- (hyprctl eval) — nothing is written to a Lua file. These settings are
-- therefore cleared on every `hyprctl reload` or session restart, and
-- must be replayed manually via
-- bash ~/.config/hypr/scripts/workspace-manager.sh (no autostart or
-- hotplug service wired to this file currently).
--
-- This module just turns on every plugged monitor at its preferred
-- mode; workspace-manager.sh then overrides scale/bitdepth/cm on the
-- detected external monitor.
-- ============================================================

hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })
