-- ============================================================
-- monitors.lua — Configuration multi-écrans dynamique & HDR
-- ============================================================
-- Aucun nom de connecteur en dur ici : l'assignation des workspaces
-- (1-7 interne / 8-10 externe) et le tuning scale/HDR de l'externe
-- sont résolus PAR RÔLE (interne = eDP*/LVDS*/DSI*, externe = le
-- reste) par scripts/workspace-manager.sh.
--
-- IMPORTANT : ce fichier ne pose que les modes de sortie de base à
-- l'exécution (hyprctl eval) — rien n'est écrit dans un fichier Lua.
-- Ces réglages sont donc effacés à chaque `hyprctl reload` ou
-- redémarrage de session, et doivent être rejoués manuellement via
-- bash ~/.config/hypr/scripts/workspace-manager.sh (pas d'autostart
-- ni de service hotplug branché sur ce fichier actuellement).
--
-- Ce module se contente d'activer tout écran branché à son mode
-- préféré ; workspace-manager.sh surcharge ensuite scale/bitdepth/cm
-- sur l'écran externe détecté.
-- ============================================================

hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })
