//! Loads a wheel definition from `~/.config/roue/wheels/<name>.toml` --
//! same format as `orbit/theme.toml`. Adding a new wheel therefore requires
//! no Rust code change at all: just a new file here and a trigger (keyboard
//! shortcut, waybar click...) that launches `roue <name>`.

use serde::Deserialize;
use std::path::PathBuf;

#[derive(Deserialize)]
pub struct WheelConfig {
    pub title: String,
    #[serde(rename = "segment")]
    pub segments: Vec<Segment>,
}

#[derive(Deserialize, Clone)]
pub struct Segment {
    pub icon: String,
    pub label: String,
    pub action: String,
    /// Destructive sector -- confirming this sector first switches the
    /// wheel to a Confirm/Cancel choice instead of launching the action
    /// right away (see wheel.rs). Absent from the TOML = false.
    #[serde(default)]
    pub confirm: bool,
    /// Tint shown when hovering this sector (fill, icon, text) -- a named
    /// color (see color.rs) or a `#rrggbb` hex code. Absent from the TOML =
    /// cyan by default. This is the field that makes the color scheme
    /// configurable wheel by wheel without touching the Rust code (e.g.
    /// wheels/powerprofile.toml: green/yellow/cyan per sector).
    #[serde(default)]
    pub accent: Option<String>,
    /// Tint of the "Confirm" sector in the sub-menu shown when `confirm` is
    /// true (see `RoueWheel::enter_confirm`) -- independent from `accent`
    /// above (which only concerns THIS sector in the root wheel): a sector
    /// can have a neutral `accent` but a red confirmation sub-menu (e.g.
    /// wheels/power.toml), or the reverse. Absent from the TOML = cyan by
    /// default, like `accent` -- only genuinely destructive sectors need to
    /// force it to "red".
    #[serde(default)]
    pub confirm_accent: Option<String>,
    /// This sector represents the system's currently applied state (e.g.
    /// the active power profile, see wheel.rs for the rendering -- a white
    /// band on the sector's outer edge). At most ONE sector should have
    /// this; if several do, the first one found wins (see
    /// `RoueWheel::new`). Not relevant for a wheel with no notion of state
    /// (e.g. wheels/power.toml: lock/shut down aren't "states") -- leave it
    /// absent everywhere in that case, no rendering change. Always
    /// regenerated by the script that writes the TOML right before opening
    /// (e.g. wheels/display.toml, never hardcoded: the real state can
    /// change between two openings).
    #[serde(default)]
    pub active: bool,
}

fn wheels_dir() -> PathBuf {
    let home = std::env::var("HOME").expect("HOME not set");
    PathBuf::from(home).join(".config/roue/wheels")
}

/// Loads the definition of wheel `name`. Fatal failure (missing file or
/// invalid TOML): unlike Prisme's keymap (`keymap.conf`, where an invalid
/// line is just ignored), a wheel with no sectors has nothing to show --
/// no sensible fallback.
pub fn load(name: &str) -> WheelConfig {
    let path = wheels_dir().join(format!("{name}.toml"));
    let content = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        eprintln!("[roue] unable to read {path:?}: {e}");
        std::process::exit(1);
    });
    toml::from_str(&content).unwrap_or_else(|e| {
        eprintln!("[roue] invalid {path:?}: {e}");
        std::process::exit(1);
    })
}
