$primary_paletteKeyColor = 328099
$secondary_paletteKeyColor = 647a83
$tertiary_paletteKeyColor = 737498
$neutral_paletteKeyColor = 73787b
$neutral_variant_paletteKeyColor = 70787c
$background = 0f1416
$onBackground = dee3e6
$surface = 0f1416
$surfaceDim = 0f1416
$surfaceBright = 353a3c
$surfaceContainerLowest = 0a0f11
$surfaceContainerLow = 171c1f
$surfaceContainer = 1b2023
$surfaceContainerHigh = 252b2d
$surfaceContainerHighest = 303638
$onSurface = dee3e6
$surfaceVariant = 40484c
$onSurfaceVariant = bfc8cc
$inverseSurface = dee3e6
$inverseOnSurface = 2c3134
$outline = 8a9296
$outlineVariant = 40484c
$shadow = 000000
$scrim = 000000
$surfaceTint = 88d1ec
$primary = 88d1ec
$onPrimary = 003543
$primaryContainer = 004e61
$onPrimaryContainer = b7eaff
$inversePrimary = 07677f
$secondary = b3cad4
$onSecondary = 1e333b
$secondaryContainer = 344a52
$onSecondaryContainer = cfe6f1
$tertiary = c3c3eb
$onTertiary = 2c2e4d
$tertiaryContainer = 8d8eb3
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = b7eaff
$primaryFixedDim = 88d1ec
$onPrimaryFixed = 001f28
$onPrimaryFixedVariant = 004e61
$secondaryFixed = cfe6f1
$secondaryFixedDim = b3cad4
$onSecondaryFixed = 071e26
$onSecondaryFixedVariant = 344a52
$tertiaryFixed = e1e0ff
$tertiaryFixedDim = c3c3eb
$onTertiaryFixed = 171837
$onTertiaryFixedVariant = 424465
$term0 = 343434
$term1 = 8383ff
$term2 = 3fe0e7
$term3 = 75fcdd
$term4 = 7ab3c5
$term5 = 7aaee9
$term6 = 82d6e3
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = a29eff
$term10 = 00f5fe
$term11 = c9fff3
$term12 = a5c7cf
$term13 = a2c0f7
$term14 = 88eaf7
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = dfe0f5
$pink = c2e0ff
$mauve = 7ac8fe
$red = 8ab5ff
$maroon = abbef0
$peach = a9daac
$yellow = d0f9f4
$green = 8beffd
$teal = a2ebfe
$sky = 9ce6ff
$sapphire = 7bd3f4
$blue = 6bc7f3
$lavender = 94d5fb
$klink = 0492ba
$klinkSelection = 0492ba
$kvisited = 0088c6
$kvisitedSelection = 0088c6
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = 34c359
$kneutralSelection = 34c359
$kpositive = 00bace
$kpositiveSelection = 00bace
$text = dee3e6
$subtext1 = bfc8cc
$subtext0 = 8a9296
$overlay2 = 787f83
$overlay1 = 656c6f
$overlay0 = 545a5d
$surface2 = 43494c
$surface1 = 32383b
$surface0 = 212628
$base = 0f1416
$mantle = 0f1416
$crust = 0e1315
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
