# --- FENÊTRE ---
window_padding_width 0 0
# On enlève les décorations de fenêtre pour un look plus "clean" avec Tmux 
hide_window_decorations yes
# 
# --- POLICE ---
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic

font_size        11.0
disable_ligatures never

# --- APPARENCE ---
background_opacity 0.85
background_blur 1
dynamic_background_opacity yes
# --- BORDURES DES FENÊTRES ---
window_border_width 1pt
active_border_color #ffb400
inactive_border_color #484e54
# Optionnel : un petit arrondi pour coller au style moderne
window_margin_width 2

# --- CURSOR (Le cœur de ta demande) ---
cursor_shape block
shell_integration no-cursor
cursor_trail 10
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# --- THÈME COULEURS (Humanoid Dark Base16) ---
foreground #f8f8f2
background #232629
selection_foreground #f8f8f2
selection_background #484e54

# Black
color0 #232629
color8 #484e54
# Red
color1 #b0151a
color9 #b0151a
# Green
color2 #028902
color10 #028902
# Yellow
color3 #ffb400
color11 #ffb400
# Blue
color4 #0082c9
color12 #0082c9
# Magenta
color5 #6d61a1
color13 #6d61a1
# Cyan
color6 #008b8b
color14 #008b8b
# White
color7 #f8f8f2
color15 #fcfcf6

# --- RACCOURCIS SYSTÈME ---
clear_all_shortcuts yes
# On garde juste le rechargement de la config
map ctrl+shift+f5 load_config_file
# Pour le copier-coller standard
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
