# =========================
# FORMAT GLOBAL
# =========================
format = """
$os\
$directory\
$git_branch\
$git_status\

$python\
$nodejs\
$java\
$rust\
$golang\
$c\
$docker_context\
$cmd_duration\
$line_break\
$character
"""

# =========================
# OS
# =========================
[os]
disabled = false
format = "[](bold white) "

# =========================
# DIRECTORY
# =========================
[directory]
format = "[ $path ](bold blue)"
truncation_length = 3
truncate_to_repo = true

# =========================
# GIT
# =========================
[git_branch]
symbol = ""
format = "[ $symbol $branch ](bold purple)"

[git_status]
format = "[ $all_status$ahead_behind ](bold red)"

# =========================
# LANGAGES
# =========================

[python]
symbol = ""
format = "[ py $version ](bg:yellow fg:black)"

[nodejs]
symbol = ""
format = "[ node $version ](bg:green fg:black)"

[java]
symbol = ""
format = "[ java $version ](bg:red fg:white)"

[rust]
symbol = ""
format = "[ rs $version ](bg:color208 fg:black)"  # orange (plus lisible que red)

[golang]
symbol = ""
format = "[ go $version ](bg:cyan fg:black)"

[c]
symbol = ""
format = ""


# =========================
# DEVOPS / ENV
# =========================

[docker_context]
format = "[ docker $context ](bg:blue fg:white)"

[kubernetes]
format = "[ k8s $context ](bg:cyan fg:black)"

# =========================
# PERF
# =========================

[cmd_duration]
min_time = 2000
format = "[ $duration ](dimmed yellow)"

# =========================
# PROMPT
# =========================

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold yellow)"